micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/ui/**"
        paths: "classpath:static"
  server:
    cors:
      enabled: true

logger:
  levels:
    io.micronaut: INFO
    io.micronaut.http: DEBUG
    org.thymeleaf: INFO
    io.netty: INFO
    nl.tabitsolutions.heatermeter.components.sensors: INFO
    nl.tabitsolutions.heatermeter.components.actuators: DEBUG
    org.sputnikdev.bluetooth.manager: INFO


jackson:
  arraySizeThreshold: 10